{% set name = "torchscan" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/torchscan-{{ version }}.tar.gz
  sha256: f71aa76fccf2379190af6b1524d27943d0b5a9b92c6881f451a1943091ba9b45

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytorch

test:
  requires:
    - python {{ python_min }}
  imports:
    - torchscan
    - torchscan.modules
    - torchscan.process
    - torchscan.utils

about:
  summary: Useful information about your Pytorch module
  home: https://github.com/frgfm/torch-scan
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
