{% set name = "torchscan" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchscan-{{ version }}.tar.gz
  sha256: acff638d5cfd639fa6838b2f61969f4206927ae9a41d6c358513c943bd2c4cfa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.6
    - pytorch

test:
  imports:
    - torchscan
    - torchscan.modules
    - torchscan.process
    - torchscan.utils

about:
  summary: Useful information about your Pytorch module
  home: https://github.com/frgfm/torch-scan
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
